### ISSUE TITLE
Проблемы при устновке

### ISSUE THREAD

**Issue by index0h** [gotlium/ahc#1]
Привет, огромное спасибо за вашу работу. Когда-то делал что-то подобное но уровнем по меньше.
Укажите пожалуйста в документации, что для Ubuntu 12.04 перед установкой необходимы пакеты libmysqlclient-dev python-dev

> sudo apt-get -y install libmysqlclient-dev python-dev

Так же проблема в Makefile:

> cp: после «/bin/sh{,.bak}» пропущен операнд, задающий целевой файл
> Попробуйте «cp --help» для получения более подробного описания.
> make: **\* [install] Ошибка

**Comment by gotlium** [comment]
Доброго времени суток. В зависимости я добавил пакеты: python-mysqldb python-pycurl python-flup. 
Это исправляет проблему.
Makefile так же поправил. Локально все отработало на ура.
Можете проверить как отработает у Вас?

**Comment by index0h** [comment]
Установка прошла успешно, спасибо.
