### ISSUE TITLE
nginx proxy apache

### ISSUE THREAD

**Issue by index0h** [gotlium/ahc#4]
Привет, судя по настройкам порта в templates/nginx-proxy-host.conf:

```
2: listen   80;
```

Рано или поздно apache и nginx будут грызться за этот 80-ый порт.
Имеет смысл использовать mod_rpaf http://adw0rd.ru/2009/nginx-and-apache-install/
Либо как вариант - apache и nginx полностью посадить на разные порты.

**Comment by gotlium** [comment]
Это заблуждение. В конфиге такая настройка:
[nginx]
port = 81
ssl_port = 444

[apache2]
port = 80
ssl_port = 443

Так что все хорошо. А приведенный тобою конфиг является хостом для проксирования.
Установить проксирование можно командой:
$ ahc -m install -s nginx_proxy
На выходе будет сообщение о смене порта apache на 8080, и то что порт нужно сменить в текущем конфиге:)

**Comment by gotlium** [comment]
Единственная проблема после будет в том, что уже ранее созданные к примеру хосты будут бадаться и не более того. Но обычно все таки подобные решения принимаются в самом начале настройке. При большом кол-ве хостов, выполняется редирект пакетов. Но это уже совсем в другой лес)

**Comment by index0h** [comment]
> Единственная проблема после будет в том, что уже ранее созданные к примеру хосты будут бадаться

Я хотел именно на этот нюанс и акцентировать внимание, в остальном же полностью согласен
