### ISSUE TITLE
deb package

### ISSUE THREAD

**Issue by index0h** [gotlium/ahc#5]
Привет, есть ли планы по созданию deb пакета для данного проекта?

**Comment by gotlium** [comment]
Привет. Думал об этом. В целом можно. Помощь конечно не помешает. Если намек на это:) Только через fake root:)

**Comment by gotlium** [comment]
Попробуй сборку http://apache-host-control.googlecode.com/files/ahc-v.1.1.0.deb

**Comment by index0h** [comment]
Software Manager пишет:

```
Этот пакет плохого качества

Lintian check results for /home/levishchenko_rv/download/ahc-v.1.1.0.deb:
Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at /usr/bin/lintian line 108.
E: ahc: maintainer-address-missing GoTLiuM InSPiRiT
```

Если игнорировать это уведомление - устанавливается успешно

**Comment by gotlium** [comment]
главное робит:) а у Software Manager все плохого качества, как и он сам:)

**Comment by index0h** [comment]
Пасиб
